name: SoapUI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-soapui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Java y SoapUI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://s3.amazonaws.com/downloads.eviware/soapuios/5.7.0/SoapUI-5.7.0-linux-bin.tar.gz
          tar -xzf SoapUI-5.7.0-linux-bin.tar.gz
          sudo mv SoapUI-5.7.0 /opt/SoapUI

      - name: Ejecutar pruebas SoapUI
        run: |
          mkdir -p reportes
          /opt/SoapUI/bin/testrunner.sh -r -j -f reportes REST-Project-2-soapui-project.xml

      - name: Subir reportes como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ReportesJUnit
          path: reportes/

      - name: Publicar resultados JUnit
        u
